name: App testing

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Unit tests
        run: bash ./gradlew testDebugUnitTest --stacktrace
      - name: Lint code
        run: bash ./gradlew lint --stacktrace
  apk:
    name: Generate APK
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Build release APK
        run: bash ./gradlew assembleRelease --stacktrace
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: app/build/outputs/apk/release/app-release-unsigned.apk
